version: 1.1.{build}-Beta
configuration: Release
pull_requests:
  do_not_increment_build_number: true
dotnet_csproj:
  patch: true
  file: '**\DbConnection.Serilog.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- ps: dotnet restore Source\DbConnection.Serilog.sln
build:
  project: Source\DbConnection.Serilog.sln
  publish_nuget: true
  verbosity: minimal